[package]
name = "rebar3_run"
version = "0.0.1"
authors = ["tristan"]

[lib]
name = "rebar3_run"
path = "src/rebar3_run.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.8.2"
rustler_codegen = "0.8.2"
